# These are supported funding model platforms

github: [yourusername]
# patreon: yourusername
# open_collective: folio-sh
# ko_fi: yourusername
# tidelift: npm/folio-sh
# community_bridge: folio-sh
# liberapay: yourusername
# issuehunt: yourusername
# lfx_crowdfunding: folio-sh
# polar: yourusername
custom: ['https://buymeacoffee.com/yourusername']
